spring.application.name=backend
server.port=8085

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/satrk?serverTimezone=Asia/Seoul}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

nexon.api.key=${NEXON_API_KEY}
nexon.api.base-url=${NEXON_API_BASE_URL:https://open.api.nexon.com}
